"""Change Hero.power to be str instead of int

Revision ID: f9cb6061fa35
Revises: a1723e69971e
Create Date: 2021-09-10 12:33:40.647489

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f9cb6061fa35'
down_revision = 'a1723e69971e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
