#!/bin/bash

# If current directory is the scripts folder, go up a folder
if [[ $(basename `pwd`) == "scripts" ]]; then
	cd ..
fi

COMMENT="$1"
if [[ -z "$COMMENT" ]]
then
    echo "ERROR: A comment is required for the alembic autogenerated migration.
       This should be passed as an argument when running this script"
    exit 1
fi


python -m alembic revision --autogenerate -m "$COMMENT"
